import Head from 'next/head'
import {BsFillMoonStarsFill, BsLinkedin,BsGithub} from 'react-icons/bs';
import Image from 'next/image';
import image from './assets/58-PrinceMangwa.jpg';
// import {profile} from 'react-pdf';



export function Home() {
  return (
    <div>
      <Head>
        <title>Prince Mangwa Sovtech Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg white px-10'>
        <section className= "bg-white-700 h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>DevelopedByPK</h1>
              <ul className='flex items-center'>
                <li>
                  
                  <BsFillMoonStarsFill/>
                </li>
                <li>
                  <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="./assets/profile.pdf" locale = {false}target= "_blank">
                  
                    Resume

                  </a>

                </li>
              </ul>
            </nav>
            <div className='text-center p-10'>
              <h2 className='text-5xl py-2 text-teal-600 font-medium'>Prince Mangwa</h2>
              <h3 className='text-2xl py-2'>Software Developer</h3>
              <p className='text-md py-5 leading-8 text-gray-800'>Software engineering student with WeThinkCode_
                proficient in java, python, HTML,CSS, ThymeLeaf,
                Software Testing just to name a few!
                do click on the links below to see my personal projects and a to find out a few things about me.
              </p>
            </div>

            <div 
              className='text-5xl flex justify-center gap-5' href="#">
              <a href='https://www.linkedin.com/in/prince-mangwa-5a928174/'><BsLinkedin/></a>
            
          
              <a href='https://github.com/KgaogeloMangwa?tab=repositories'><BsGithub/></a>
              
            </div>

            <div className='relative mx-auto bg-gradiet-to-b from-teal-500 rounded-full w-80 h-80 mt-20'>
              <Image src={image}  alt="MyPicture"/>

              <h3 className='text-2xl py-2'>Why i want to work for Sovtech</h3>
              <p className='text-md py-5 leading-8 text-gray-800'> Reasons i want to work for Sovtechis because i see what they 
              offering as a potential growth path for me in improving my skills and growing as a software developer,this is based 
              on what they are offering through their graduate program.

              I believe that through the program any and all potential of me being a well renowned software developer 
              is going to show its self through the program which will be highlighted by my dedication.
              </p>

            </div>

        </section>

      </main>
    </div>
  )
}

export default Home;